global:
  scrape_interval: 60s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'nvidia-gpu-exporter'
    static_configs:
      - targets: ['alex-desktop:9835']

  - job_name: ethermine-ethermine-miner
    # Limit due to API rate restriction
    scrape_interval: 5m
    metrics_path: /miner
    params:
      pool: [ethermine]
    static_configs:
      - targets:
          # TODO List your ETH addresses here
          - 0000000000000000000000000000000000000000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # TODO Point this to your exporter
        replacement: alex-desktop:8080